export const ALL_CROPS_LIST: string[] = [
  'Cotton',
  'Soybean',
  'Sugarcane',
  'Rice',
  'Wheat',
  'Tomato',
  'Chickpea',
  'Onion',
  'Potato',
  'Maize',
  'Pigeon Pea',
  'Groundnut',
  'Brinjal',
  'Chili',
  'Cabbage',
  'Cauliflower',
  'Okra',
  'Mustard',
  'Sunflower',
  'Banana',
  'Mango',
  'Cashew',
  'Coffee',
  'Cucumber',
  'Garlic',
  'Ginger',
  'Grape',
  'Melon',
  'Papaya',
  'Bell Pepper',
  'Tea',
  'Apple',
  'Orange',
];

export const ALL_CROPS_CONFIG = ALL_CROPS_LIST.map((name) => ({
  id: name.toLowerCase().replace(/\s+/g, '_'),
  name,
}));
